"""
Synthetic data generator + LSTM trainer for the KPI classifier.

Run standalone to produce kpi_model.pt:
    py train.py

Or imported and called from kpi_agent.py at startup:
    from train import train_model
    model = train_model("kpi_model.pt")

Synthetic data strategy
-----------------------
Each class is generated by sampling time-series around class-specific
mean/std vectors for the 6 KPI features.  A small temporal correlation
is added within each sequence so the LSTM learns *trends*, not just
point-in-time snapshots.
"""

import os
import logging
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

from model import KPIClassifier, SEQ_LEN, N_FEATURES, N_CLASSES, LABELS, normalise

log = logging.getLogger(__name__)

SAMPLES_PER_CLASS = 2500
EPOCHS            = 50
BATCH_SIZE        = 256
LR                = 1e-3

# Feature order: prb_dl_pct, sinr_db, connected_ues, power_w, packet_loss_pct, throughput_dl_mbps

_CLASS_SPECS: list[tuple[list, list]] = [
    # Class 0  NORMAL
    ([50,  18, 200, 150, 0.4,  500], [15, 5, 80, 30, 0.4,  150]),
    # Class 1  OVERLOAD
    ([92,  10, 420, 215, 7.0,  860], [ 4, 3, 55, 22, 3.5,   70]),
    # Class 2  UNDERLOAD
    ([10,  22,  12, 130, 0.1,   80], [ 5, 5,  6, 18, 0.1,   40]),
    # Class 3  SINR_LOW
    ([50,   1, 150, 175, 22.0, 190], [20, 2, 70, 30, 7.0,   90]),
    # Class 4  POWER_WASTE
    ([15,  22,   9, 205, 0.1,   95], [ 7, 5,  4, 28, 0.1,   45]),
]


def _make_sequence(means: list, stds: list) -> list[list[float]]:
    """One sample: SEQ_LEN steps around means with temporal drift."""
    base = np.array(means) + np.random.randn(N_FEATURES) * np.array(stds) * 0.5
    seq  = []
    for _ in range(SEQ_LEN):
        step = base + np.random.randn(N_FEATURES) * np.array(stds) * 0.15
        step = np.clip(step, 0, None)
        seq.append(normalise(step.tolist()))
        # slow drift so consecutive readings are correlated
        base += np.random.randn(N_FEATURES) * np.array(stds) * 0.05
    return seq


def generate_data() -> tuple[np.ndarray, np.ndarray]:
    np.random.seed(0)
    X, y = [], []
    for label, (means, stds) in enumerate(_CLASS_SPECS):
        for _ in range(SAMPLES_PER_CLASS):
            X.append(_make_sequence(means, stds))
            y.append(label)
    X = np.array(X, dtype=np.float32)
    y = np.array(y, dtype=np.int64)
    idx = np.random.permutation(len(y))
    return X[idx], y[idx]


def train_model(save_path: str = "kpi_model.pt") -> KPIClassifier:
    log.info("Generating synthetic data: %d samples × %d classes …",
             SAMPLES_PER_CLASS, N_CLASSES)
    X, y = generate_data()

    split  = int(len(y) * 0.8)
    X_tr, X_va = torch.tensor(X[:split]), torch.tensor(X[split:])
    y_tr, y_va = torch.tensor(y[:split]), torch.tensor(y[split:])

    train_dl = DataLoader(TensorDataset(X_tr, y_tr), batch_size=BATCH_SIZE, shuffle=True)
    val_dl   = DataLoader(TensorDataset(X_va, y_va), batch_size=BATCH_SIZE)

    model     = KPIClassifier()
    criterion = nn.CrossEntropyLoss()
    optimiser = torch.optim.Adam(model.parameters(), lr=LR)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimiser, T_max=EPOCHS)

    log.info("Training bidirectional LSTM for %d epochs …", EPOCHS)
    for epoch in range(1, EPOCHS + 1):
        model.train()
        total_loss = 0.0
        for xb, yb in train_dl:
            optimiser.zero_grad()
            loss = criterion(model(xb), yb)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimiser.step()
            total_loss += loss.item()
        scheduler.step()

        if epoch % 10 == 0 or epoch == EPOCHS:
            model.eval()
            correct = 0
            with torch.no_grad():
                for xb, yb in val_dl:
                    correct += (model(xb).argmax(1) == yb).sum().item()
            acc = correct / len(y_va) * 100
            log.info("  epoch %2d/%d — loss %.4f — val-acc %.1f%%",
                     epoch, EPOCHS, total_loss / len(train_dl), acc)

    torch.save(model.state_dict(), save_path)
    log.info("Model weights saved → %s", save_path)

    # Per-class accuracy breakdown
    model.eval()
    class_correct = [0] * N_CLASSES
    class_total   = [0] * N_CLASSES
    with torch.no_grad():
        for xb, yb in val_dl:
            preds = model(xb).argmax(1)
            for pred, true in zip(preds, yb):
                class_total[true.item()]   += 1
                class_correct[true.item()] += int(pred == true)
    for cls in range(N_CLASSES):
        if class_total[cls]:
            log.info("  %-12s  %3d / %3d  (%.0f%%)",
                     LABELS[cls],
                     class_correct[cls], class_total[cls],
                     class_correct[cls] / class_total[cls] * 100)

    return model


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    train_model()
